export type AppSettings = {
  aiApiKey: string;
  aiBaseUrl: string;
  aiModel: string;
  aiImageModel: string;
  aiAudioModel: string;
  aiDefaultSystemPrompt: string;
  aiRequestTimeoutMs: number;
  aiMaxRetries: number;
  aiContextMessageLimit: number;
  pdfPreviewCharLimit: number;
  knowledgeBaseEnabled: boolean;
  knowledgeBasePath: string;
  knowledgeUseEmbeddings: boolean;
  knowledgeEmbeddingModel: string;
  webSearchEnabled: boolean;
  devModeEnabled: boolean;
  configDir: string;
  maxImagesPerMessage: number;
  maxImageBytes: number;
};

export type UpdateSettingsInput = {
  aiApiKey: string;
  aiBaseUrl: string;
  aiModel: string;
  aiImageModel: string;
  aiAudioModel: string;
  aiDefaultSystemPrompt: string;
  aiRequestTimeoutMs: number;
  aiMaxRetries: number;
  aiContextMessageLimit: number;
  pdfPreviewCharLimit: number;
  knowledgeBaseEnabled: boolean;
  knowledgeBasePath: string;
  knowledgeUseEmbeddings: boolean;
  knowledgeEmbeddingModel: string;
  webSearchEnabled: boolean;
  devModeEnabled: boolean;
};
